services:
  - type: worker
    name: drm-decrypt-bot
    env: python
    buildCommand: "chmod +x N_m3u8DL-RE && pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: API_ID
        value: "your_api_id"
      - key: API_HASH
        value: "your_api_hash"
      - key: BOT_TOKEN
        value: "your_bot_token"
